name: test
run-name: testing 
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare Test Environment
      run: |
        cd assignoperation
        mkdir -p ignore_test_file
        mv src/test/java/vehiclemgmt_20241126_1/*.java ignore_test_file/ || true
        mv ignore_test_file/DistanceCalculationTest.java src/test/java/vehiclemgmt_20241126_1/ || true
    - name: Compile and Run Specific Test
      run: |
        cd assignoperation
        mvn test-compile
        mvn test -Dtest=vehiclemgmt_20241126_1.DistanceCalculationTest -Dsurefire.useFile=false
    - name: Restore Test Files
      if: always()
      run: |
        cd assignoperation
        if [ -d "ignore_test_file" ] && [ "$(ls -A ignore_test_file)" ]; then
          mv ignore_test_file/*.java src/test/java/vehiclemgmt_20241126_1/
        fi
        rm -rf ignore_test_file
    - name: Print Test Results
      if: always()
      run: |
        cd assignoperation
        cat target/surefire-reports/*.txt || true